2019-05-10 17:01:51,389 ERROR: Exception on /menu/armadopika [GET] [in /home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/franzisca/PycharmProjects/pyflaskapp/flask1/routes.py", line 72, in menu_armadopika
    pikas=pikas
UnboundLocalError: local variable 'pikas' referenced before assignment
2019-05-29 10:43:10,852 ERROR: Exception on /menu/stockpikas [GET] [in /home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 221, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'nombre'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/franzisca/PycharmProjects/pyflaskapp/flask1/routes.py", line 119, in menu_stockpikas
    DATA = db.query(StockPika).order_by(StockPika.pika.nombre).all()
  File "/home/franzisca/PycharmProjects/pyflaskapp/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 230, in __getattr__
    key,
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with StockPika.pika has an attribute 'nombre'
